name: 'Lockfile'
description: 'Forbid non-npm lockfiles'
runs:
    using: composite
    steps:
        - name: Check lockfiles
          uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
          with:
              script: |
                  const {existsSync} = require('fs');
                  ['yarn.lock', 'pnpm-lock.yaml'].forEach(forbiddenLockFile => {
                    if(existsSync(forbiddenLockFile)) {
                      const error = `Lockfile ${forbiddenLockFile} is not allowed in this repo, remove it.`;
                      core.error(
                        error,
                        {title: 'Forbidden lockfile', file: forbiddenLockFile}
                      );
                      process.exitCode=1
                    }
                  });
