name: 'Setup'
description: 'Install Node & NPM dependencies'
runs:
    using: composite
    steps:
        - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
          with:
              node-version-file: '.nvmrc'
              cache: npm
              registry-url: 'https://registry.npmjs.org'
        - run: npm ci
          shell: bash
