name: 'Setup'
description: 'Install Node & NPM dependencies'
runs:
    using: composite
    steps:
        - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
          with:
              node-version-file: '.nvmrc'
              cache: npm
              registry-url: 'https://registry.npmjs.org'
        - run: npm ci
          shell: bash
