name: 'Setup'
description: 'Install Node & NPM dependencies'
runs:
    using: composite
    steps:
        - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
          with:
              node-version-file: '.nvmrc'
              cache: npm
              registry-url: 'https://registry.npmjs.org'
        - run: npm ci
          shell: bash
