name: 'Setup'
description: 'Install Node & NPM dependencies'
runs:
    using: composite
    steps:
        - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
          with:
              node-version-file: '.nvmrc'
              cache: npm
              registry-url: 'https://registry.npmjs.org'
        - run: npm ci
          shell: bash
