name: 'Setup'
description: 'Install Node & NPM dependencies'
runs:
    using: composite
    steps:
        - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
          with:
              node-version-file: '.nvmrc'
              cache: npm
              registry-url: 'https://registry.npmjs.org'
        - run: npm ci
          shell: bash
