language: node_js

node_js:
  - lts/*

branches:
    only:
        - master

stages:
  - analyse commits
  - test
  - name: release
    if: branch = master

jobs:
  include:
    - stage: analyse commits
      script: commitlint-travis
    - stage: test
      script: npm test
    - stage: release
      script: npm run build
      deploy:
        skip_cleanup: true
        provider: script
        script: npm run release
