language: node_js

node_js:
    - lts/*

jobs:
    include:
        - stage: test
          script: commitlint-travis
          script: npm test

        - stage: release
          script: npm run build
          on:
            branch: master
          deploy:
              skip_cleanup: true
              provider: script
              script: npm run release
