name: 'Dependency Review'
on:
    pull_request:
        branches: ['master']
    merge_group:

permissions:
    contents: read
    pull-requests: write

jobs:
    dependency-review:
        uses: coveo/public-actions/.github/workflows/dependency-review.yml@main
        with:
            public: true
            distributed: true
            base-ref: ${{ github.event.pull_request.base.sha || 'master' }}
            head-ref: ${{ github.event.pull_request.head.sha || github.ref_name }}
