name: 'Renovate Config Validator'

on:
    push:
        branches: [master]
        paths:
            - 'renovate.json'
    pull_request:
        branches: [master]
        paths:
            - 'renovate.json'

permissions:
    contents: read

jobs:
    renovate-config:
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
              with:
                  egress-policy: audit

            - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
            - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
              with:
                  cache: 'npm'
                  node-version-file: '.nvmrc'
            - name: Check Renovate config
              run: |
                  npm i renovate
                  node_modules/.bin/renovate-config-validator
